---
version: 4.+
repository_root: "{default.repository.root}/app-dynamics"
default_application_name: 
default_node_name: $(ruby -e "require 'json' ; a = JSON.parse(ENV['VCAP_APPLICATION']);
  puts \"#{a['application_name']}:#{a['instance_index']}\"")
default_tier_name: 
